services:
  backend:
    build: ./backend
    container_name: backend_container
    ports:
      - '8081:8081'
    volumes:
      - ./backend:/main
      - /main/node_modules
  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/main
      - /main/node_modules
    stdin_open: true
    tty: true
  db:
    image: mysql
    container_name: db_container
    environment:
      MYSQL_DATABASE: duewallet
    ports:
      - '3306:3306'
    volumes:
    - db_data:/main
  phpMyAdmin:
    image: phpmyadmin
    container_name: pma_container
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - '80:80'
volumes:
  db_data: